logging:
    level:
        org:
            apache:
                http: DEBUG
        httpclient:
            wire: DEBUG
openai:
    model: gpt-3.5-turbo
    api:
        key: ${OPENAI_API_KEY}
        url: https://api.openai.com/v1/chat/completions